### ISSUE TITLE
stdio使用问题

### ISSUE THREAD

**Issue by hy2z** [daizhirui/CamelStudio_Library#1]
stdio结构有点乱，stdio_shared.h好像没有地方使用到，stdio_shared.c中的函数原型放在在stdio.h中是为了和标准库使用方法保持一致？建议把stdio_shared.c中的函数原型放在stdio_shared.h中，在stdio.h中引入头文件。
```
D:/CamelStudioRelease/CamelStudio/lib/M2\libstr.a(str.o): In function `puts':
str.c:(.text+0xe4): multiple definition of `puts'
release/stdio_fp.o:stdio_fp.c:(.text+0x58): first defined here
D:/CamelStudioRelease/CamelStudio/lib/M2\libstr.a(str.o): In function `getnum':
str.c:(.text+0x4b4): multiple definition of `getnum'
release/stdio_fp.o:stdio_fp.c:(.text+0x138): first defined here
```
在win上链接str.o库会有重复定义的错误

**Comment by hy2z** [comment]
因为这部分编译时是默认链接的，interrupt.o用到了其中的getch函数，那么stdio_shared.c不该再有定义了。

**Comment by daizhirui** [comment]
If you want to use stdio library, the best choice is to use the whole library I develop. In the library of Windows version studio, in order to implement debug function, some functions about printing are designed and they have the same name as stdio's. If you don't need debug, the best choice is to replace M2 library with this library. And change the library name of m2core to mcu.
Because there are two versions of stdio library, one has float and the other doesn't. It is better to keep some shared functions in stdio_share.
